# https://github.com/marketplace/actions/close-stale-issues
name: "Stale issues"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
permissions:
  issues: write

jobs:
  stale:
    if: github.repository == 'aws/copilot-cli'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          # issue configuration
          stale-issue-message: "This issue is stale because it has been open 60 days with no response activity. Remove the stale label, add a comment, or this will be closed in 14 days."
          close-issue-message: "This issue is closed due to inactivity. Feel free to reopen the issue if you have any further questions!"
          days-before-issue-stale: 60
          days-before-issue-close: 14
          stale-issue-label: "stale"
          any-of-issue-labels: "pending/question, guidance"

          # pr configuration (disabled)
          days-before-pr-stale: -1
          days-before-pr-close: -1
